name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      # Ruff : Python Linter and Formatter (Checks)
      - name: Install Ruff
        run: uv tool install ruff

      - name: Check code formatting
        run: ruff format --check .

      - name: Lint code
        run: ruff check .
      # End of Ruff Checks

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Run pytest - test_agent_logic
        run: uv run pytest src/tests/test_unit/test_agent_logic.py

      - name: Run pytest - test_mcp_server_strat_pred
        run: uv run pytest src/tests/test_unit/test_mcp_server_strat_pred.py
